namespace SharpAI.Engines
{
    using System;
    using System.Diagnostics;
    using System.IO;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.CompilerServices;
    using System.Text;
    using System.Threading;
    using System.Threading.Tasks;
    using LLama;
    using LLama.Common;
    using LLama.Native;
    using LLama.Sampling;
    using SharpAI.Classes.Runtime;
    using SharpAI.Prompts;
    using SharpAI.Telemetry;
    using SyslogLogging;

    /// <summary>
    /// LlamaSharp implementation of the AI provider base class.
    /// Provides text generation, embeddings, and chat completion using the LlamaSharp library.
    /// </summary>
    public class LlamaSharpEngine : EngineBase, IChatTemplateSource
    {
        #region Public-Members

        /// <summary>
        /// Boolean indicating if the engine is disposed.
        /// </summary>
        public override bool IsDisposed
        {
            get
            {
                return _Disposed;
            }
        }
        
        /// <summary>
        /// Gets the number of dimensions in the embedding vectors generated by this engine.
        /// Returns -1 if not yet determined, 0 if embeddings are not supported.
        /// </summary>
        public override int EmbeddingDimensions
        {
            get
            {
                if (_EmbeddingDimensions == -1 && _Embedder != null)
                {
                    // Get embedding dimensions by testing with a small input
                    try
                    {
                        IReadOnlyList<float[]> testEmbeddings = _Embedder.GetEmbeddings("test").Result;
                        float[] testEmbedding = testEmbeddings.Single();
                        _EmbeddingDimensions = testEmbedding.Length;
                    }
                    catch
                    {
                        _EmbeddingDimensions = 0;
                    }
                }
                return _EmbeddingDimensions;
            }
        }

        /// <summary>
        /// Gets a value indicating whether this engine supports GPU acceleration.
        /// LlamaSharp supports GPU acceleration when CUDA is available.
        /// </summary>
        public override bool SupportsGpu => true;

        /// <summary>
        /// Gets a value indicating whether this engine supports generating embeddings.
        /// Determined by inspecting the GGUF architecture and pooling-type metadata.
        /// </summary>
        public override bool SupportsEmbeddings => DetectSupportsEmbeddings();

        /// <summary>
        /// Gets a value indicating whether this engine supports text generation.
        /// Determined by inspecting the GGUF architecture metadata. Pure embedding
        /// architectures (BERT family, T5 encoder, etc.) return false.
        /// </summary>
        public override bool SupportsGeneration => DetectSupportsGeneration();

        /// <summary>
        /// Gets the GGUF <c>general.architecture</c> value from the loaded model, or null if unavailable.
        /// </summary>
        public string Architecture
        {
            get
            {
                if (_Model == null || _Model.Metadata == null) return null;
                if (_Model.Metadata.TryGetValue("general.architecture", out string arch)) return arch;
                return null;
            }
        }

        /// <summary>
        /// Gets whether this engine has been successfully initialized.
        /// </summary>
        public override bool IsInitialized => _IsInitialized;

        /// <summary>
        /// Gets whether the loaded model carries a usable embedded chat template (GGUF
        /// <c>tokenizer.chat_template</c>). The result is probed once and cached. Returns false before the
        /// engine is initialized.
        /// </summary>
        public bool SupportsEmbeddedChatTemplate
        {
            get
            {
                if (_HasEmbeddedTemplate.HasValue) return _HasEmbeddedTemplate.Value;
                if (!_IsInitialized || _Model == null) return false;

                try
                {
                    LLamaTemplate probe = new LLamaTemplate(_Model, true);
                    _HasEmbeddedTemplate = probe != null;
                }
                catch
                {
                    _HasEmbeddedTemplate = false;
                }

                return _HasEmbeddedTemplate ?? false;
            }
        }

        /// <summary>
        /// Number of tokens to generate when a caller does not specify a positive value.
        /// Applied only when the requested maximum is zero or negative; a positive request is honored
        /// exactly (including small values). Default 512, minimum 1.
        /// </summary>
        public int DefaultMaxTokens
        {
            get
            {
                return _DefaultMaxTokens;
            }
            set
            {
                if (value < 1) throw new ArgumentOutOfRangeException(nameof(DefaultMaxTokens), "DefaultMaxTokens must be at least 1.");
                _DefaultMaxTokens = value;
            }
        }

        /// <summary>
        /// Whether inputs longer than the embedding context are split into chunks and averaged. Default
        /// true. When false, an over-length embedding input throws instead of being silently chunked and
        /// averaged, which changes the resulting vector's meaning.
        /// </summary>
        public bool EnableEmbeddingChunking
        {
            get
            {
                return _EnableEmbeddingChunking;
            }
            set
            {
                _EnableEmbeddingChunking = value;
            }
        }

        /// <summary>
        /// Maximum number of generations that may run concurrently against this model. Default 1 (strictly
        /// serialized). Values above 1 allow parallel decode slots; this must be set before the engine is
        /// initialized to take effect. Minimum 1.
        /// </summary>
        public int MaxConcurrentGenerations
        {
            get
            {
                return _MaxConcurrentGenerations;
            }
            set
            {
                if (value < 1) throw new ArgumentOutOfRangeException(nameof(MaxConcurrentGenerations), "MaxConcurrentGenerations must be at least 1.");
                _MaxConcurrentGenerations = value;
            }
        }

        /// <summary>
        /// Milliseconds a generation request waits for a free slot before it is rejected with an
        /// <see cref="SharpAI.Exceptions.EngineBusyException"/>. Default 0, which waits indefinitely.
        /// Minimum 0.
        /// </summary>
        public int GenerationQueueTimeoutMs
        {
            get
            {
                return _GenerationQueueTimeoutMs;
            }
            set
            {
                if (value < 0) throw new ArgumentOutOfRangeException(nameof(GenerationQueueTimeoutMs), "GenerationQueueTimeoutMs may not be negative.");
                _GenerationQueueTimeoutMs = value;
            }
        }

        /// <summary>
        /// Gets the context window size (maximum number of tokens) for this model.
        /// </summary>
        /// <returns>The context window size in tokens, or -1 if not available.</returns>
        public override int GetContextSize()
        {
            if (!_IsInitialized || _Context == null)
                return -1;

            return (int)_Context.ContextSize;
        }

        /// <summary>
        /// Count tokens in <paramref name="text"/> using the provider's tokenizer.
        /// </summary>
        /// <param name="text">Input text to tokenize.</param>
        /// <param name="addBos">Whether to include a beginning-of-sentence token.</param>
        /// <param name="parseSpecial">Whether to parse special tokens (e.g., &lt;|im_start|&gt;).</param>
        /// <returns>Total token count; 0 if the engine is not initialized.</returns>
        public override int CountTokens(string text, bool addBos = true, bool parseSpecial = true)
        {
            if (!_IsInitialized || _Context == null || string.IsNullOrEmpty(text))
                return 0;
            try
            {
                LLamaToken[] toks = _Context.Tokenize(text, addBos, parseSpecial);
                return toks.Length;
            }
            catch
            {
                return Math.Max(1, text.Length / 4);
            }
        }

        #endregion

        #region Private-Members

        private string _Header = "[LlamaSharpEngine] ";
        private LoggingModule _Logging = null;

        private LLamaWeights _Model = null;
        private LLamaContext _Context = null;
        private LLamaWeights _EmbeddingModel = null;
        private LLamaEmbedder _Embedder = null;
        private InteractiveExecutor _Executor = null;
        private StatelessExecutor _StatelessExecutor = null;
        private ChatSession _ChatSession = null;
        private bool _IsInitialized = false;
        private bool _Disposed = false;
        private int _EmbeddingDimensions = -1;
        private int _DefaultMaxTokens = 512;
        private bool _EnableEmbeddingChunking = true;
        private int _GpuLayers = 0;
        private bool _EmbedderLoadAttempted = false;
        private bool? _HasEmbeddedTemplate = null;
        private int _MaxConcurrentGenerations = 1;
        private int _GenerationQueueTimeoutMs = 0;
        private readonly SemaphoreSlim _EmbedderSemaphore = new SemaphoreSlim(1, 1);
        private readonly SemaphoreSlim _EmbedderInitSemaphore = new SemaphoreSlim(1, 1);
        private SemaphoreSlim _GenerationSemaphore = new SemaphoreSlim(1, 1);
        #endregion

        #region Constructors-and-Factories

        /// <summary>
        /// Initializes a new instance of the LlamaSharpEngine class.
        /// </summary>
        /// <param name="logging">Optional logging module for capturing debug and error information. If null, a new LoggingModule will be created.</param>
        public LlamaSharpEngine(LoggingModule logging = null)
        {
            _Logging = logging ?? new LoggingModule();

            _Logging.Debug(_Header + "initialized");
        }

        #endregion

        #region Public-Methods

        /// <summary>
        /// Releases all resources used by the LlamaSharpEngine.
        /// Properly disposes of the model, context, and embedder instances.
        /// </summary>
        public override void Dispose()
        {
            if (_Disposed) return;

            try
            {
                _ChatSession = null;
                _Executor = null;
                _StatelessExecutor = null;

                _Embedder?.Dispose();
                _EmbeddingModel?.Dispose();
                _Context?.Dispose();
                _Model?.Dispose();

                _EmbedderSemaphore?.Dispose();
                _EmbedderInitSemaphore?.Dispose();
                _GenerationSemaphore?.Dispose();
            }
            catch (Exception ex)
            {
                _Logging.Warn(_Header + "disposal exception:" + Environment.NewLine + ex.ToString());
            }
            finally
            {
                _Disposed = true;
                _IsInitialized = false;
            }
        }

        #region Initialization

        /// <summary>
        /// Initializes the LlamaSharp engine with the specified model file.
        /// Loads the model, creates context, and sets up executors for text generation and embeddings.
        /// </summary>
        /// <param name="modelPath">The file path to the GGUF model file to load.</param>
        /// <returns>A task that represents the asynchronous initialization operation.</returns>
        /// <exception cref="Exception">Thrown when the model fails to load or initialize.</exception>
        public override async Task InitializeAsync(string modelPath)
        {
            if (_IsInitialized) return;

            ModelPath = modelPath;

            await Task.Run(() =>
            {
                try
                {
                    int gpuLayers = GetOptimalGpuLayers();
                    _Logging.Debug(_Header + $"initializing LlamaSharp with {(gpuLayers != 0 ? $"GPU ({gpuLayers} layers requested)" : "CPU")}");

                    ModelParams parameters = CreateModelParams(modelPath, gpuLayers, false, true);

                    _Model = LLamaWeights.LoadFromFile(parameters);
                    _Context = _Model.CreateContext(parameters);

                    _Executor = new InteractiveExecutor(_Context); // text generation
                    _StatelessExecutor = new StatelessExecutor(_Model, parameters); // text generation
                    _ChatSession = new ChatSession(_Executor);

                    // Embeddings load lazily on first use (see EnsureEmbedderAsync). A generation-only
                    // model never allocates the second copy of the weights that a dedicated embedding
                    // context requires.
                    _GpuLayers = gpuLayers;

                    // Concurrency and admission configuration (env overrides the property defaults).
                    _MaxConcurrentGenerations = SharpAIEnvironment.GetInt(SharpAIEnvironment.MaxConcurrentGenerations, _MaxConcurrentGenerations, 1);
                    _GenerationQueueTimeoutMs = SharpAIEnvironment.GetInt(SharpAIEnvironment.GenerationQueueTimeoutMs, _GenerationQueueTimeoutMs, 0);
                    if (_MaxConcurrentGenerations > 1)
                    {
                        _GenerationSemaphore.Dispose();
                        _GenerationSemaphore = new SemaphoreSlim(_MaxConcurrentGenerations, _MaxConcurrentGenerations);
                    }
                    _Logging.Debug(_Header + $"generation slots={_MaxConcurrentGenerations}, queueTimeoutMs={_GenerationQueueTimeoutMs}");

                    _IsInitialized = true;

                    _Logging.Debug(_Header + "LlamaSharp provider initialized successfully");
                }
                catch (Exception ex)
                {
                    throw new Exception("failed to initialize LlamaSharp:" + Environment.NewLine + ex.ToString());
                }
            });
        }

        /// <summary>
        /// Determines the optimal number of GPU layers to use based on available hardware.
        /// </summary>
        /// <returns>The number of GPU layers to use, or 0 if GPU acceleration is not available. Returns -1 to use all available GPU layers.</returns>
        public override int GetOptimalGpuLayers()
        {
            try
            {
                // Check which backend was selected by NativeLibraryBootstrapper
                string selectedBackend = SharpAI.Classes.Runtime.NativeBackendInfo.SelectedBackend;

                if (selectedBackend.Equals("cuda", StringComparison.OrdinalIgnoreCase)
                    || selectedBackend.Equals("metal", StringComparison.OrdinalIgnoreCase))
                {
                    long gpuDeviceCount = LLama.Native.NativeApi.llama_max_devices();
                    _Logging.Debug(_Header + $"{selectedBackend} backend selected, {gpuDeviceCount} GPU device(s) available");

                    string configuredGpuLayers = SharpAIEnvironment.GetString(SharpAIEnvironment.GpuLayers);
                    if (!String.IsNullOrEmpty(configuredGpuLayers)
                        && !configuredGpuLayers.Equals("auto", StringComparison.OrdinalIgnoreCase))
                    {
                        if (Int32.TryParse(configuredGpuLayers, out int parsedGpuLayers) && parsedGpuLayers >= -1)
                        {
                            if (parsedGpuLayers == -1)
                            {
                                _Logging.Debug(_Header + "GPU layer override requests all layers");
                                return 999;
                            }

                            _Logging.Debug(_Header + $"GPU layer override requests {parsedGpuLayers} layer(s)");
                            return parsedGpuLayers;
                        }

                        _Logging.Warn(_Header + $"{SharpAIEnvironment.GpuLayers} value '" + configuredGpuLayers + "' is invalid, using automatic GPU layer selection");
                    }

                    return 999; // big positive -> clamp to all layers
                }
                else
                {
                    _Logging.Debug(_Header + $"{selectedBackend} backend selected, using CPU");
                    return 0;
                }
            }
            catch (Exception ex)
            {
                _Logging.Debug(_Header + "GPU detection exception, using CPU:" + Environment.NewLine + ex.ToString());
                return 0;
            }
        }

        #endregion

        #region Runtime-Parameters

        private ModelParams CreateModelParams(string modelPath, int gpuLayers, bool embeddings, bool logParams)
        {
            int threads = GetConfiguredThreadCount();
            int batchThreads = SharpAIEnvironment.GetInt(SharpAIEnvironment.BatchThreads, threads, 1);
            int mainGpu = SharpAIEnvironment.GetInt(SharpAIEnvironment.MainGpu, -1, 0);
            uint contextSize = SharpAIEnvironment.GetUInt(SharpAIEnvironment.ContextSize, 0, 0);
            uint batchSize = SharpAIEnvironment.GetUInt(SharpAIEnvironment.BatchSize, 0, 0);
            uint uBatchSize = SharpAIEnvironment.GetUInt(SharpAIEnvironment.UBatchSize, 0, 0);
            bool useMmap = SharpAIEnvironment.GetBool(SharpAIEnvironment.UseMmap, true);
            bool useMlock = SharpAIEnvironment.GetBool(SharpAIEnvironment.UseMlock, false);
            bool flashAttention = SharpAIEnvironment.GetBool(SharpAIEnvironment.FlashAttention, false);

            ModelParams parameters = new ModelParams(modelPath)
            {
                GpuLayerCount = gpuLayers,
                Threads = threads,
                BatchThreads = batchThreads,
                Embeddings = embeddings,
                UseMemorymap = useMmap,
                UseMemoryLock = useMlock,
                FlashAttention = flashAttention
            };

            if (mainGpu >= 0) parameters.MainGpu = mainGpu;
            if (contextSize > 0) parameters.ContextSize = contextSize;
            if (batchSize > 0) parameters.BatchSize = batchSize;
            if (uBatchSize > 0) parameters.UBatchSize = uBatchSize;

            if (logParams)
            {
                _Logging.Debug(_Header + "model params: "
                    + "threads=" + threads
                    + ", batchThreads=" + batchThreads
                    + ", gpuLayers=" + gpuLayers
                    + ", mainGpu=" + (mainGpu >= 0 ? mainGpu.ToString() : "auto")
                    + ", contextSize=" + (contextSize > 0 ? contextSize.ToString() : "model-default")
                    + ", batchSize=" + (batchSize > 0 ? batchSize.ToString() : "default")
                    + ", uBatchSize=" + (uBatchSize > 0 ? uBatchSize.ToString() : "default")
                    + ", useMmap=" + useMmap
                    + ", useMlock=" + useMlock
                    + ", flashAttention=" + flashAttention
                    + ", embeddings=" + embeddings);
            }

            return parameters;
        }

        private int GetConfiguredThreadCount()
        {
            int defaultThreads = Math.Max(1, Environment.ProcessorCount - 1);
            return SharpAIEnvironment.GetInt(SharpAIEnvironment.NumThreads, defaultThreads, 1);
        }

        #endregion

        #region Embeddings

        /// <inheritdoc />
        public override async Task<int> GetDimensionality(CancellationToken token = default)
        {
            ThrowIfNotInitialized();

            await EnsureEmbedderAsync(token).ConfigureAwait(false);

            IReadOnlyList<float[]> embeddings = await _Embedder.GetEmbeddings("test", token).ConfigureAwait(false);
            return embeddings[0].Length;
        }

        /// <inheritdoc />
        public override async Task<float[]> GenerateEmbeddingsAsync(
            string text,
            CancellationToken token = default)
        {
            ThrowIfNotInitialized();

            await EnsureEmbedderAsync(token).ConfigureAwait(false);

            // Handle long texts by chunking and averaging
            return await ProcessTextWithChunking(text, token).ConfigureAwait(false);
        }

        /// <inheritdoc />
        public override async Task<float[][]> GenerateEmbeddingsAsync(string[] texts, CancellationToken token = default(CancellationToken))
        {
            ThrowIfNotInitialized();

            await EnsureEmbedderAsync(token).ConfigureAwait(false);

            float[][] embeddings = new float[texts.Length][];
            for (int i = 0; i < texts.Length; i++)
            {
                float[][] array = embeddings;
                int num = i;
                array[num] = await ProcessTextWithChunking(texts[i], token).ConfigureAwait(continueOnCapturedContext: false);
            }

            return embeddings;
        }

        #endregion

        #region Text Generation

        /// <inheritdoc />
        public override async Task<string> GenerateTextAsync(
            string prompt,
            int maxTokens = 512,
            float temperature = 0.7f,
            string[] stopSequences = null,
            CancellationToken token = default)
        {
            ThrowIfNotInitialized();

            Stopwatch stopwatch = Stopwatch.StartNew();
            bool success = false;
            long tokenCount = 0;

            await AcquireGenerationSlotAsync(token).ConfigureAwait(false);
            try
            {
                InferenceParams inferenceParams = new InferenceParams
                {
                    MaxTokens = EffectiveMaxTokens(maxTokens),
                    AntiPrompts = stopSequences?.ToList() ?? new List<string>(),
                    SamplingPipeline = new DefaultSamplingPipeline
                    {
                        Temperature = temperature
                    }
                };

                StringBuilder result = new StringBuilder();

                await foreach (string curr in _StatelessExecutor.InferAsync(prompt, inferenceParams, token).ConfigureAwait(false))
                {
                    result.Append(curr);
                }

                string text = result.ToString().Trim();
                success = true;
                tokenCount = CountTokens(text, false, false);
                return text;
            }
            catch (Exception ex)
            {
                _Logging.Warn(_Header + "exception generating text:" + Environment.NewLine + ex.ToString());
                throw new Exception($"Failed to generate text:{Environment.NewLine}{ex.ToString()}", ex);
            }
            finally
            {
                _GenerationSemaphore.Release();
                stopwatch.Stop();
                SharpAITelemetry.RecordInference("completion", TelemetryModelLabel(), stopwatch.Elapsed.TotalSeconds, tokenCount, success);
            }
        }

        /// <inheritdoc />
        public override async IAsyncEnumerable<string> GenerateTextStreamAsync(
            string prompt,
            int maxTokens = 512,
            float temperature = 0.7f,
            string[] stopSequences = null,
            [EnumeratorCancellation] CancellationToken token = default)
        {
            ThrowIfNotInitialized();

            Stopwatch stopwatch = Stopwatch.StartNew();
            bool success = false;
            long tokenCount = 0;

            await AcquireGenerationSlotAsync(token).ConfigureAwait(false);
            try
            {
                InferenceParams inferenceParams = new InferenceParams
                {
                    MaxTokens = EffectiveMaxTokens(maxTokens),
                    AntiPrompts = stopSequences?.ToList() ?? new List<string>(),
                    SamplingPipeline = new DefaultSamplingPipeline
                    {
                        Temperature = temperature
                    }
                };

                await foreach (string curr in _StatelessExecutor.InferAsync(prompt, inferenceParams, token).ConfigureAwait(false))
                {
                    tokenCount++;
                    yield return curr;
                }

                success = true;
            }
            finally
            {
                _GenerationSemaphore.Release();
                stopwatch.Stop();
                SharpAITelemetry.RecordInference("completion", TelemetryModelLabel(), stopwatch.Elapsed.TotalSeconds, tokenCount, success);
            }
        }

        #endregion

        #region Chat

        /// <inheritdoc />
        public override async Task<string> GenerateChatCompletionAsync(
            string prompt,
            int maxTokens = 512,
            float temperature = 0.7f,
            string[] stopSequences = null,
            CancellationToken token = default)
        {
            ThrowIfNotInitialized();

            Stopwatch stopwatch = Stopwatch.StartNew();
            bool success = false;
            long tokenCount = 0;

            await AcquireGenerationSlotAsync(token).ConfigureAwait(false);
            try
            {
                InferenceParams inferenceParams = new InferenceParams
                {
                    MaxTokens = EffectiveMaxTokens(maxTokens),
                    AntiPrompts = stopSequences?.ToList() ?? new List<string> { "user:", "User:", "human:", "Human:" }, // Default anti-prompt for chat
                    SamplingPipeline = new DefaultSamplingPipeline
                    {
                        Temperature = temperature
                    }
                };

                StringBuilder result = new StringBuilder();

                await foreach (string curr in _StatelessExecutor!.InferAsync(prompt, inferenceParams, token).ConfigureAwait(false))
                {
                    result.Append(curr);
                }

                string text = result.ToString().Trim();
                success = true;
                tokenCount = CountTokens(text, false, false);
                return text;
            }
            catch (Exception ex)
            {
                _Logging.Warn(_Header + "exception generating chat completion:" + Environment.NewLine + ex.ToString());
                throw new Exception($"Failed to generate chat completion:{Environment.NewLine}{ex.ToString()}", ex);
            }
            finally
            {
                _GenerationSemaphore.Release();
                stopwatch.Stop();
                SharpAITelemetry.RecordInference("chat", TelemetryModelLabel(), stopwatch.Elapsed.TotalSeconds, tokenCount, success);
            }
        }

        /// <inheritdoc />
        public override async IAsyncEnumerable<string> GenerateChatCompletionStreamAsync(
            string prompt,
            int maxTokens = 512,
            float temperature = 0.7f,
            string[] stopSequences = null,
            [EnumeratorCancellation] CancellationToken token = default)
        {
            ThrowIfNotInitialized();

            Stopwatch stopwatch = Stopwatch.StartNew();
            bool success = false;
            long tokenCount = 0;

            await AcquireGenerationSlotAsync(token).ConfigureAwait(false);
            try
            {
                InferenceParams inferenceParams = new InferenceParams
                {
                    MaxTokens = EffectiveMaxTokens(maxTokens),
                    AntiPrompts = stopSequences?.ToList() ?? new List<string> { "user:", "User:", "human:", "Human:" }, // Default anti-prompt for chat
                    SamplingPipeline = new DefaultSamplingPipeline
                    {
                        Temperature = temperature
                    }
                };

                await foreach (string curr in _StatelessExecutor!.InferAsync(prompt, inferenceParams, token).ConfigureAwait(false))
                {
                    tokenCount++;
                    yield return curr;
                }

                success = true;
            }
            finally
            {
                _GenerationSemaphore.Release();
                stopwatch.Stop();
                SharpAITelemetry.RecordInference("chat", TelemetryModelLabel(), stopwatch.Elapsed.TotalSeconds, tokenCount, success);
            }
        }

        #endregion

        #region Chat-Template

        /// <inheritdoc />
        public string RenderEmbeddedChatPrompt(IReadOnlyList<ChatMessage> messages, bool addGenerationPrompt)
        {
            if (messages == null) throw new ArgumentNullException(nameof(messages));
            if (!_IsInitialized || _Model == null) throw new InvalidOperationException("Model is not initialized.");

            LLamaTemplate template = new LLamaTemplate(_Model, true);
            template.AddAssistant = addGenerationPrompt;

            foreach (ChatMessage message in messages)
            {
                if (message == null) continue;
                string role = String.IsNullOrEmpty(message.Role) ? "user" : message.Role;
                template.Add(role, message.Content ?? String.Empty);
            }

            ReadOnlySpan<byte> rendered = template.Apply();
            return Encoding.UTF8.GetString(rendered);
        }

        #endregion

        #endregion

        #region Private-Methods

        private bool DetectSupportsEmbeddings()
        {
            // If the GGUF declares a pooling type (mean/cls/last/rank) it is authoritative:
            // llama.cpp only sets this for models that produce sentence-level embeddings.
            if (_Model?.Metadata != null &&
                _Model.Metadata.TryGetValue("general.pooling_type", out string pooling) &&
                !string.IsNullOrEmpty(pooling) && pooling != "-1" && pooling != "none")
            {
                return true;
            }

            string arch = Architecture;
            if (!string.IsNullOrEmpty(arch) && SharpAI.Helpers.GgufMetadataReader.EmbeddingOnlyArchitectures.Contains(arch))
            {
                return true;
            }

            return false;
        }

        private bool DetectSupportsGeneration()
        {
            string arch = Architecture;
            if (!string.IsNullOrEmpty(arch) && SharpAI.Helpers.GgufMetadataReader.EmbeddingOnlyArchitectures.Contains(arch))
            {
                return false;
            }

            // Default: any decoder-capable model (llama, qwen2, mistral, phi3, gemma, ...) supports generation.
            return true;
        }

        private async Task<float[]> ProcessTextWithChunking(string text, CancellationToken token)
        {
            if (string.IsNullOrWhiteSpace(text))
                throw new ArgumentException("Text cannot be null or empty", nameof(text));

            int contextSize = (int)(_EmbeddingModel?.ContextSize ?? 512);
            int tokenLimit = (int)(contextSize * 0.8);
            int charLimit = tokenLimit * 3;

            async Task<float[]> TryEmbed(string input)
            {
                await _EmbedderSemaphore.WaitAsync(token).ConfigureAwait(false);
                try
                {
                    return (await _Embedder.GetEmbeddings(input, token).ConfigureAwait(false)).Single();
                }
                finally
                {
                    _EmbedderSemaphore.Release();
                }
            }

            try
            {
                if (text.Length <= charLimit)
                {
                    return await TryEmbed(text).ConfigureAwait(false);
                }

                if (!_EnableEmbeddingChunking)
                {
                    throw new InvalidOperationException(
                        $"Embedding input of {text.Length} characters exceeds the model's context (~{charLimit} chars) and chunking is disabled. " +
                        "Shorten the input or enable EnableEmbeddingChunking to chunk and average.");
                }

                _Logging?.Debug(_Header + $"processing long text ({text.Length} chars) in chunks (limit: {charLimit})");
                List<string> chunks = SplitTextIntoChunks(text, charLimit);
                List<float[]> embeddings = new List<float[]>();

                foreach ((string chunk, int index) in chunks.Select((c, i) => (c, i)))
                {
                    try
                    {
                        embeddings.Add(await TryEmbed(chunk).ConfigureAwait(false));
                    }
                    catch (ArgumentException ex) when (ex.Message.Contains("Embedding prompt is longer"))
                    {
                        _Logging?.Warn(_Header + $"chunk {index + 1} too long after split, retrying with smaller chunks");
                        int retryLimit = charLimit / 2;
                        List<string> subChunks = SplitTextIntoChunks(chunk, retryLimit);
                        foreach (string subChunk in subChunks)
                        {
                            embeddings.Add(await TryEmbed(subChunk).ConfigureAwait(false));
                        }
                    }
                    catch (Exception ex)
                    {
                        _Logging?.Error(_Header + $"failed to process chunk {index + 1}: {ex.Message}");
                        throw new InvalidOperationException($"Failed to process text chunk {index + 1}/{chunks.Count}: {ex.Message}", ex);
                    }
                }

                return AverageEmbeddings(embeddings);
            }
            catch (Exception ex)
            {
                _Logging?.Error(_Header + "exception during fallback chunked embedding: " + ex.Message);
                throw;
            }
        }

        private List<string> SplitTextIntoChunks(string text, int maxCharacters)
        {
            List<string> chunks = new List<string>();
            int currentIndex = 0;

            while (currentIndex < text.Length)
            {
                int chunkSize = Math.Min(maxCharacters, text.Length - currentIndex);
                string chunk = text.Substring(currentIndex, chunkSize);

                if (currentIndex + chunkSize < text.Length && !char.IsWhiteSpace(text[currentIndex + chunkSize]))
                {
                    int lastSpaceIndex = chunk.LastIndexOf(' ');
                    if (lastSpaceIndex > chunkSize / 2)
                    {
                        chunk = chunk.Substring(0, lastSpaceIndex);
                        chunkSize = lastSpaceIndex;
                    }
                }

                chunks.Add(chunk.Trim());
                currentIndex += chunkSize;

                while (currentIndex < text.Length && char.IsWhiteSpace(text[currentIndex]))
                {
                    currentIndex++;
                }
            }

            _Logging?.Debug(_Header + $"split text into {chunks.Count} chunks");
            return chunks;
        }

        private float[] AverageEmbeddings(List<float[]> embeddings)
        {
            if (embeddings == null || embeddings.Count == 0)
            {
                throw new ArgumentException("Embeddings list cannot be null or empty", nameof(embeddings));
            }

            if (embeddings.Count == 1)
            {
                return embeddings[0];
            }

            int dimensions = embeddings[0].Length;
            float[] averaged = new float[dimensions];

            foreach (float[] embedding in embeddings)
            {
                if (embedding.Length != dimensions)
                {
                    throw new InvalidOperationException("all embeddings must have the same dimensions");
                }

                for (int i = 0; i < dimensions; i++)
                {
                    averaged[i] += embedding[i];
                }
            }

            for (int i = 0; i < dimensions; i++)
            {
                averaged[i] /= embeddings.Count;
            }

            return averaged;
        }

        private void ThrowIfNotInitialized()
        {
            if (!_IsInitialized) throw new InvalidOperationException("Provider must be initialized before use. Call InitializeAsync() first.");
            if (_Disposed) throw new ObjectDisposedException(nameof(LlamaSharpEngine));
        }

        private string TelemetryModelLabel()
        {
            string arch = Architecture;
            if (!String.IsNullOrEmpty(arch)) return arch;
            if (!String.IsNullOrEmpty(ModelPath)) return Path.GetFileNameWithoutExtension(ModelPath);
            return "unknown";
        }

        private int EffectiveMaxTokens(int requested)
        {
            // Honor any positive request exactly, including small values (e.g. max_tokens=8). Only fall
            // back to the configured default when the caller did not specify a positive maximum.
            if (requested > 0) return requested;
            return _DefaultMaxTokens;
        }

        private async Task AcquireGenerationSlotAsync(CancellationToken token)
        {
            if (_GenerationQueueTimeoutMs <= 0)
            {
                await AcquireGenerationSlotAsync(token).ConfigureAwait(false);
                return;
            }

            bool acquired = await _GenerationSemaphore.WaitAsync(_GenerationQueueTimeoutMs, token).ConfigureAwait(false);
            if (!acquired)
                throw new SharpAI.Exceptions.EngineBusyException(
                    $"All {_MaxConcurrentGenerations} generation slot(s) are busy; timed out after {_GenerationQueueTimeoutMs} ms.");
        }

        private async Task EnsureEmbedderAsync(CancellationToken token)
        {
            if (_Embedder != null) return;

            await _EmbedderInitSemaphore.WaitAsync(token).ConfigureAwait(false);
            try
            {
                if (_Embedder != null) return;

                if (_EmbedderLoadAttempted)
                    throw new InvalidOperationException("Embeddings are not supported. The embedder failed to initialize.");

                _EmbedderLoadAttempted = true;

                await Task.Run(() =>
                {
                    ModelParams embeddingParams = CreateModelParams(ModelPath, _GpuLayers, true, false);
                    _EmbeddingModel = LLamaWeights.LoadFromFile(embeddingParams);
                    _Embedder = new LLamaEmbedder(_EmbeddingModel, embeddingParams);
                }, token).ConfigureAwait(false);

                _Logging.Debug(_Header + "embedding model loaded on demand");
            }
            catch (Exception ex)
            {
                _Logging.Warn(_Header + "failed to initialize embeddings:" + Environment.NewLine + ex.ToString());

                try { _Embedder?.Dispose(); } catch { }
                try { _EmbeddingModel?.Dispose(); } catch { }
                _Embedder = null;
                _EmbeddingModel = null;

                throw new InvalidOperationException("Embeddings are not supported. The embedder failed to initialize.", ex);
            }
            finally
            {
                _EmbedderInitSemaphore.Release();
            }
        }

        #endregion
    }
}
