export const completionOptions = {
  num_keep: 5,
  seed: 42,
  num_predict: 1024,
  top_k: 20,
  top_p: 0.9,
  min_p: 0.0,
  tfs_z: 0.5,
  typical_p: 0.7,
  repeat_last_n: 33,
  temperature: 0.8,
  repeat_penalty: 1.2,
  presence_penalty: 1.5,
  frequency_penalty: 1.0,
  mirostat: 1,
  mirostat_tau: 0.8,
  mirostat_eta: 0.6,
  penalize_newline: true,
  // Common chat template delimiters to stop generation at the end of an assistant turn
  stop: [
    "user:",
    "User:",
    "USER:",
    "[INST]",
    "[/INST]",
    "<|im_end|>",
    "<|endoftext|>",
    "<|eot_id|>",
    "</s>",
  ],
  numa: false,
  num_ctx: 4096,
  num_batch: 2,
  num_gpu: 1,
  main_gpu: 0,
  low_vram: false,
  display_thinking: false,
  f16_kv: true,
  vocab_only: false,
  use_mmap: true,
  use_mlock: false,
  num_thread: 8,
};
